# Generated by Django 5.2.15 on 2026-06-05 05:06

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('raw_name', models.CharField(max_length=200)),
                ('item_number', models.CharField(blank=True, max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('discount', 'Discount')], default='product', max_length=16)),
                ('taxable', models.BooleanField(default=False)),
                ('tracking_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('untracked', 'Untracked'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['receipt', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='receipts/%Y/%m/')),
                ('store_location', models.CharField(blank=True, max_length=200)),
                ('store_number', models.CharField(blank=True, max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('invoice_number', models.CharField(blank=True, max_length=32)),
                ('raw_parse', models.JSONField(blank=True, default=dict)),
                ('parse_status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('parse_error', models.TextField(blank=True)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
