# Generated by Django 5.2.15 on 2026-06-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('receipts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='pricing.product'),
        ),
    ]
