# Generated by Django 5.2.15 on 2026-06-05 16:16

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('observed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('within_adjustment_window', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('seen', 'Seen'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='receipts.lineitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'line_item'), name='uniq_user_lineitem_alert')],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_sale', models.BooleanField(default=False)),
                ('source', models.CharField(default='provider', max_length=32)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='pricing.product')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['product', '-observed_at'], name='pricing_pri_product_ff0784_idx')],
            },
        ),
    ]
