# Generated by Django 5.2.15 on 2026-06-06 05:38

from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    """Accounts that predate email verification are treated as verified."""
    User = apps.get_model("users", "User")
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            grandfather_existing_users, migrations.RunPython.noop
        ),
    ]
